###
get http://127.0.0.1:8000/api/articles


###
post http://127.0.0.1:8000/api/post_article
Content-Type: application/json

{
    "title": "test api",
    "content": "desc"
}


###
put http://127.0.0.1:8000/api/update/1
Content-Type: application/json

{
    "title": "test api",
    "content": "desc"
}


###
delete http://127.0.0.1:8000/api/delete/1